# Generated by Django 5.1.2 on 2024-10-14 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_class_count', models.PositiveIntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('discount_limit', models.IntegerField(blank=True, null=True)),
                ('reward_type', models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage'), ('additional_service', 'Additional Service'), ('point', 'Point'), ('amount_on_specific_classroom', 'Amount on Specific Classroom'), ('amount_on_specific_department', 'Amount on Specific Department'), ('amount_on_specific_category', 'Amount on Specific Category'), ('percentage_on_specific_classroom', 'Percentage on Specific Classroom'), ('percentage_on_specific_department', 'Percentage on Specific Department'), ('percentage_on_specific_category', 'Percentage on Specific Category'), ('register_in_specific_classroom', 'Register in Specific Classroom')], max_length=255)),
                ('additional_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_models.additionalservice')),
            ],
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
