# Generated by Django 5.1.2 on 2024-10-14 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pointrole',
            name='point_role_type',
            field=models.CharField(choices=[('number_of_classrooms', 'Number of Classrooms'), ('number_of_classrooms_with_specific_department', 'Number of Classrooms with Specific Department'), ('number_of_classrooms_with_specific_category', 'Number of Classrooms with Specific Category')], default='number_of_classrooms', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointrole',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loyalty_models.pointrolegroup'),
        ),
    ]
