# Generated by Django 5.1.2 on 2024-10-15 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0006_additionalservice_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pointrole',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='point_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointrole',
            name='user_logs',
            field=models.ManyToManyField(blank=True, related_name='used_point_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointrolegroup',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='point_role_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointrole',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poit_roles', to='loyalty_models.pointrolegroup'),
        ),
        migrations.AlterField(
            model_name='pointrole',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='loyalty_models.rewards'),
        ),
    ]
