# Generated by Django 5.1.2 on 2024-10-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0008_remove_pointrolegroup_user_alter_userpoints_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoints',
            old_name='points',
            new_name='point',
        ),
    ]
