# Generated by Django 5.1.2 on 2024-10-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0011_alter_userpoints_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_points', models.PositiveIntegerField()),
                ('reward', models.ManyToManyField(related_name='tiers', to='loyalty_models.rewards')),
            ],
        ),
        migrations.AddField(
            model_name='userpoints',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='loyalty_models.tiers'),
        ),
    ]
