# Generated by Django 5.1.2 on 2024-10-15 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0012_tiers_userpoints_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPoints',
            new_name='UserPoint',
        ),
        migrations.AlterField(
            model_name='pointrole',
            name='point_role_type',
            field=models.CharField(choices=[('number_of_purchases', [('number_of_purchases', 'Number of Classrooms'), ('number_of_purchases_with_specific_classroom', 'Number of Classrooms with Specific Classroom'), ('number_of_purchases_with_specific_department', 'Number of Classrooms with Specific Department'), ('number_of_purchases_with_specific_category', 'Number of Classrooms with Specific Category'), ('number_of_purchases_with_specific_work_group', 'Number of Classrooms with Specific Work Group')])], max_length=255),
        ),
    ]
