# Generated by Django 5.1.2 on 2024-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0013_rename_userpoints_userpoint_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiers',
            new_name='Tier',
        ),
    ]
