# Generated by Django 5.1.2 on 2024-10-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0015_rename_rewards_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointrole',
            old_name='min_class_count',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='pointrole',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_roles', to='loyalty_models.pointrolegroup'),
        ),
        migrations.AlterField(
            model_name='pointrole',
            name='point_role_type',
            field=models.CharField(choices=[('Number of Purchases', [('number_of_purchases', 'Number of Purchases'), ('number_of_purchases_with_specific_classroom', 'Number of Classrooms with Specific Classroom'), ('number_of_purchases_with_specific_department', 'Number of Classrooms with Specific Department'), ('number_of_purchases_with_specific_category', 'Number of Classrooms with Specific Category'), ('number_of_purchases_with_specific_work_group', 'Number of Classrooms with Specific Work Group')]), ('Average Score', [('avg_score', 'Average Score'), ('avg_score_in_specific_classroom', 'Average Score in Specific Classroom'), ('avg_score_in_specific_department', 'Average Score in Specific Department'), ('avg_score_in_specific_work_group', 'Average Score in Specific Work Group'), ('avg_score_in_specific_category', 'Average Score in Specific Category')]), ('First in Class', [('num_of_first_in_class', 'Num of First in Class'), ('num_of_first_in_class', 'Num of First in Class in Specific Classroom'), ('num_of_first_in_class', 'Num of First in Class in Specific Department'), ('num_of_first_in_class', 'Num of First in Class in Specific Work Group'), ('num_of_first_in_class_in_specific_category', 'Num of First in Class in Specific Work Category')])], max_length=255),
        ),
    ]
