# Generated by Django 5.1.2 on 2024-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_models', '0016_rename_min_class_count_pointrole_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointrole',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='pointrole',
            name='point_role_type',
            field=models.CharField(choices=[('Number of Purchases', [('number_of_purchases', 'Number of Purchases')]), ('Average Score', [('avg_score', 'Average Score')]), ('First in Class', [('num_of_first_in_class', 'Num of First in Class')])], max_length=255),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('additional_service', 'Additional Service'), ('point', 'Point')], max_length=255),
        ),
    ]
